sudo: required

env:
  global:
    jwBvg4wyA78ZWMN70LmHbXDwbH7VnctodvZGwlIvCDqQ+LwXIwutEITHUhA54+nnaJ8Oj5T/qKtUmnVx+Uq/yU54NQwaBfmHozoyZFJB6jTKjI2uLbQjDl9FIv/vH5PUTnEOG6n9aqcW63yQnt2k2ikEhUQGXSeom5sfGaDJnywhIk8Rdbhaq4mdSEHi4xo61ZZoNCK7Sjms5vh4BowZDR/AH3kNXyZ35DaQK1YOthIhWq9LqlbHfhHyYZ0E2ZuJll68zcYqcRgAyGS04IhKuWb0Bs4qXZxQ4sk90DOJ8zdY2meA7FUAdeD4cLrsUfJUn6/+oKB8RCYI1BDAgobH5K8cHTVeelCcymaUcuSU1vhN9MiumYyyRwrNa3l4PUknoyLCq2o3biMBRUqOz9v6JfQd6SOyif9+CExPZXi6CZt5/bp9sy+RyU65StR1s1TulufZ9dU6WybDiXpQtbTyRHQfVdnr2duPReTk2fsn0zFdxSbqgyIeg/oJBvoYSFnJD/SFO9UTfuyXtOYBRKH4k0f81IrRa0/RQAGtAAXi1W+npw4m3I0CjSjB32RNM2Z/HTwTJZyRen2hfrG3TVzk/qCDyCvOqKoR7YG74jxtBa8hAD82RE468SjjOtgS9GW4YT0RnY438IeCUKcn98Iqdo1AQpA+zI+S0o6FyAZpX0I=

branches:
  only:
    - master
    - /^\d+\.\d+\.\d+(-.+)?$/

before_install:
  - ./run.sh install-tools

script:
  - |
    export BUILD_NUMBER=$(TZ=":US/Eastern" date '+%Y%m%d%H%M%S')
    export IS_FINAL_BUILD=false
    if [ ! -z "$TRAVIS_TAG" ]; then
      export IS_FINAL_BUILD=true
    fi
    ./build.sh "/p:BuildNumber=${BUILD_NUMBER}" "/p:IsFinalBuild=${IS_FINAL_BUILD}"

deploy:
  - provider: script
    skip_cleanup: true
    script: ./dotnet-run.sh dotnet nuget push "./artifacts/build/*.nupkg" --api-key "$MYGET_KEY" --source "https://www.myget.org/F/pomelo/api/v3/index.json"
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: ./dotnet-run.sh dotnet nuget push "./artifacts/build/*.nupkg" --api-key "$MYGET_KEY" --source "https://www.myget.org/F/pomelo/api/v3/index.json"
    on:
      tags: true

notifications:
  email: false
