sudo: required

env:
  global:
    secure: "lEKYkmy692zsvFZpYqyZ7peX8JsbRBZeIyNmmSoFovIB8XP3i8PpI6fqRLeYUZWQyR4dAK9zX9mZtB5giSDo+CtZztHdzRMHIJzLWEHa1FVqScqBUBrDG3VKRS1nq3jKGvqgV7Mq8YL6DWOVxgpGUnJwr9Oee7JvKywTabyJkSzhl9DFZIl6A14yOyV3bEfC5xDhIyaoeMrobKQXnvmpLEKsQym6kmPT+IPq1yuCZQZ1Ul16WrNVg58xy8So40FTvSQSLiUkG1CRaj0j4KlUB8cvRFIer9DIx3P9Wt61prHAr/25/DMlV6lVqyM129L4YOW65uBBVe+Q9LAWUymqH5KxbmcE7a6m15E6k7izaNkYC5HexmP9rlpLzReH9M0k+nCduj3pHkDN6JjNxOqdO6zCl7L4MvvC8g8HOBtz7hfYPCW4wL8WVP3TyGn6qWmMOXIEak4H8snmQGxRT26+ydfIsdwBNdA6Vm7v6jLBGWygvyQrNky97hTnfm9eXMTm0Kc99mq0UFuCa8g9rysRn4st9i85SqkjWqqPypIm9l1tW05VnZhvi2LuzWLCit1V8z1YaywkUi+VB5L/UkZbmsBygpe9AVaxMQYVGZFsHfoEWrZx0/Xfjtog9u9/4jA3eGX35pKIah1cVf2v4F5m11PS06YxirEa5fRs16pZED4="

branches:
  only:
    - master
    - /^\d+\.\d+\.\d+(-.+)?$/

before_install:
  - ./run.sh install-tools

script:
  - |
    export BUILD_NUMBER=$(TZ=":US/Eastern" date '+%Y%m%d%H%M%S')
    export IS_FINAL_BUILD=false
    if [ ! -z "$TRAVIS_TAG" ]; then
      export IS_FINAL_BUILD=true
    fi
    ./build.sh "/p:BuildNumber=${BUILD_NUMBER}" "/p:IsFinalBuild=${IS_FINAL_BUILD}"

deploy:
  - provider: script
    skip_cleanup: true
    script: ./dotnet-run.sh dotnet nuget push "./artifacts/build/*.nupkg" --api-key "$MYGET_KEY" --source "https://www.myget.org/F/pomelo/api/v3/index.json"
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: ./dotnet-run.sh dotnet nuget push "./artifacts/build/*.nupkg" --api-key "$MYGET_KEY" --source "https://www.myget.org/F/pomelo/api/v3/index.json"
    on:
      tags: true

notifications:
  email: false
